<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net4.7.2</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms><LangVersion>9.0</LangVersion>
    <AssemblyName>XDM-Setup</AssemblyName><PlatformTarget>AnyCPU</PlatformTarget><Prefer32Bit>false</Prefer32Bit>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\XDM.Wpf.UI\xdm-logo.ico</ApplicationIcon>
    <DebugType>none</DebugType><DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp"/>
    <Reference Include="System.Net.Http"/><Reference Include="System.Web.Extensions"/>
    <Reference Include="System.IO.Compression"/><Reference Include="System.IO.Compression.FileSystem"/>
    <EmbeddedResource Include="$(InstallerWork)\xdm-x86.msi" LogicalName="xdm-x86.msi"/>
    <EmbeddedResource Include="$(InstallerWork)\xdm-x64.msi" LogicalName="xdm-x64.msi"/>
    <EmbeddedResource Include="$(ReleaseConfigPath)" LogicalName="release-config.json"/>
    <EmbeddedResource Include="$(InstallerWork)\package-hashes.json" LogicalName="package-hashes.json"/>
  </ItemGroup>
</Project>
